object-storage-kit:
  storage-type: s3 # Options: s3, minio
  
  # ==========================================
  # UNIFIED COMMON PROPERTIES FOR S3 & MINIO
  # ==========================================
  
  # Connection settings
  endpoint: # Custom endpoint URL (e.g., http://localhost:9000 for MinIO, https://s3.amazonaws.com for AWS S3)
  region: us-east-1 # AWS region for S3, can be any value for MinIO
  path-style-access: false # Set to true for MinIO or older S3 configurations
  
  # Authentication
  access-key: # Access key ID
  secret-key: # Secret access key
  session-token: # Optional: Session token for temporary credentials
  
  # Default bucket configuration
  default-bucket: # Default bucket name for operations
  auto-create-bucket: false # Whether to automatically create bucket if it doesn't exist
  
  # Connection and timeout settings
  connection-timeout-millis: 10000 # Connection timeout in milliseconds
  socket-timeout-millis: 50000 # Socket timeout in milliseconds
  
  # Transfer acceleration (S3 only)
  accelerate-mode-enabled: false # Enable S3 Transfer Acceleration
  dual-stack-enabled: false # Enable dual-stack endpoints (IPv4 and IPv6)
  
  # Additional headers and metadata
  user-agent-prefix: # Custom user agent prefix
  user-agent-suffix: # Custom user agent suffix
  
  # Examples for different environments:
  # AWS S3:
  #   endpoint: https://s3.amazonaws.com (or leave blank for default)
  #   region: us-east-1
  #   path-style-access: false
  #
  # MinIO:
  #   endpoint: http://localhost:9000
  #   region: us-east-1 (any value works)
  #   path-style-access: true
  #   access-key: minioadmin
  #   secret-key: minioadmin
  #
  # S3-Compatible Services (like DigitalOcean Spaces):
  #   endpoint: https://nyc3.digitaloceanspaces.com
  #   region: nyc3
  #   path-style-access: false